/**
 * Client-side corpus loader. Imports the build-time bundled corpus
 * (`data/verbs/_corpus.client.json`, generated by `scripts/build-corpus.ts`)
 * and configures the engine in the browser bundle. Used by Client
 * Components that need to call `conjugate()` (e.g., the playground).
 *
 * Server-side rendering uses `lib/corpus.ts` instead, which reads
 * per-verb files via `node:fs`. Both code paths consume the same
 * source-of-truth — the per-verb files under `data/verbs/<lemma>.json`.
 */

import { configure, type VerbEntry } from '@foljapp/engine';

import corpusData from '../../../data/verbs/_corpus.client.json';
import versionData from '../../../data/verbs/version.json';

const CORPUS = corpusData as VerbEntry[];

let configured = false;

export function ensureClientConfigured(): void {
  if (configured) return;
  configure(CORPUS, (versionData as { version: string }).version);
  configured = true;
}

// Configure eagerly on module load so any consumer sees a ready engine.
ensureClientConfigured();

export function findClientEntry(lemma: string): VerbEntry | undefined {
  return CORPUS.find((e) => e.lemma === lemma);
}
