/**
 * JSON-backed corpus bundle for environments without `node:fs`.
 *
 * The file is generated by `scripts/build-corpus.ts` from the same
 * per-verb source files that `lib/corpus.ts` reads on the server.
 * Client components and Edge route handlers both use this module.
 */

import { configure, type VerbEntry } from '@foljapp/engine';

import corpusData from '../../../data/verbs/_corpus.client.json';
import versionData from '../../../data/verbs/version.json';

import { decodeVerbSlug } from './verb-route';

interface CorpusVersion {
  version: string;
  generatedAt: string;
  engineVersion: string;
}

export const bundledCorpus = corpusData as VerbEntry[];
export const bundledCorpusVersion = versionData as CorpusVersion;

let configured = false;

export function ensureBundledCorpusConfigured(): void {
  if (configured) return;
  configure(bundledCorpus, bundledCorpusVersion.version);
  configured = true;
}

// Configure eagerly on module load so consumers see a ready engine.
ensureBundledCorpusConfigured();

export function findBundledEntryByLemma(lemma: string): VerbEntry | undefined {
  return bundledCorpus.find((e) => e.lemma === lemma);
}

export function findBundledEntryBySlug(slug: string): VerbEntry | undefined {
  const decoded = decodeVerbSlug(slug);
  return bundledCorpus.find((e) => e.id === decoded || e.lemma === decoded);
}

export function allBundledLemmas(): string[] {
  return bundledCorpus.map((e) => e.lemma).sort();
}
